# Generated by Django 3.2 on 2023-02-06 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_auto_20230206_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        10, message="Максимальная оценка должна быть не более 10"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Минимальная оценка должна быть не менее 1"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
