# Generated by Django 3.2 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_auto_20230206_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="rating",
            field=models.IntegerField(null=True, verbose_name="rating"),
        ),
    ]
